name: Setup Bun
description: Reduce boilerplate when setting up Bun and installing dependencies.
author: Mark Skelton
branding:
  icon: play
  color: blue
inputs:
  flags:
    description: Additional flags to pass to the `bun install` command.
  bun-version:
    description: Bun version to use, defaults to the latest version.
    default: latest
  ref:
    description: Git ref to checkout. Passed to `actions/checkout`.
  fetch-depth:
    description: Fetch depth of the checkout. Passed to `actions/checkout`.
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - name: Setup Bun ${{ inputs.node-version }}
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile ${{ inputs.flags }}
